# Generated by Django 4.1.7 on 2023-04-11 14:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chitchat', '0003_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='users',
            field=models.ManyToManyField(through='chitchat.Subscription', to=settings.AUTH_USER_MODEL),
        ),
    ]
