# Generated by Django 4.1.7 on 2023-06-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chitchat', '0006_alter_author_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Enter a category name', max_length=50, unique=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_en_us',
            field=models.CharField(help_text='Enter a category name', max_length=50, null=True, unique=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_ru',
            field=models.CharField(help_text='Enter a category name', max_length=50, null=True, unique=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_category',
            field=models.ManyToManyField(through='chitchat.PostCategory', to='chitchat.category', verbose_name='Category'),
        ),
    ]
